### ISSUE TITLE
Triangulation fails with a very simple polygon

### ISSUE THREAD

**Issue by mattbeghin** [jhasse/poly2tri#10]
I've been using this library since a while without problems, after having handled constraints, but I found this very simple polygon which makes the library (current master) crash:

    std::vector<p2t::Point*> polyline = {
        new p2t::Point(-0.611580879999999993401615938637,0.0104235565411950892311665484158),
        new p2t::Point(-0.611580879999999993401615938637,0.1483950316905975341796875),
        new p2t::Point(-0.578899596898762469621146919962,0.227294628589359948289683188705),
        new p2t::Point(-0.5,0.259975911690597527581303438637),
        new p2t::Point(0.5,0.259975911690597527581303438637),
        new p2t::Point(0.578899596898762469621146919962,0.227294628589359948289683188705),
        new p2t::Point(0.611580879999999993401615938637,0.1483950316905975341796875),
        new p2t::Point(0.611580879999999993401615938637,0.0104235565411950614755909327869),
        new p2t::Point(0.388419120000000006598384061363,0.0104235565411950892311665484158),
        new p2t::Point(0.388419120000000006598384061363,0.0368141516905975130224959457337),
        new p2t::Point(-0.388419120000000006598384061363,0.0368141516905975269002837535481),
        new p2t::Point(-0.388419120000000006598384061363,0.0104235565411950892311665484158)
    };

    p2t::CDT cdt(polyline);
    cdt.Triangulate();

<img width="470" alt="Screenshot 2019-12-05 at 13 20 21" src="https://user-images.githubusercontent.com/16778892/70235329-0e757000-1763-11ea-85c7-5840b3b14d58.png">

You can check the WKT of the polygon (for instance here http://dev.openlayers.org/examples/vector-formats.html):
POLYGON((-0.611580879999999993401615938637 0.0104235565411950892311665484158,-0.611580879999999993401615938637 0.1483950316905975341796875,-0.578899596898762469621146919962 0.227294628589359948289683188705,-0.5 0.259975911690597527581303438637,0.5 0.259975911690597527581303438637,0.578899596898762469621146919962 0.227294628589359948289683188705,0.611580879999999993401615938637 0.1483950316905975341796875,0.611580879999999993401615938637 0.0104235565411950614755909327869,0.388419120000000006598384061363 0.0104235565411950892311665484158,0.388419120000000006598384061363 0.0368141516905975130224959457337,-0.388419120000000006598384061363 0.0368141516905975269002837535481,-0.388419120000000006598384061363 0.0104235565411950892311665484158,-0.611580879999999993401615938637 0.0104235565411950892311665484158))

**Comment by mattbeghin** [comment]
Still the same issue with this simple example:
LINESTRING(0.9636984967276516 0.7676550649687783,0.9636984967276516 -0.7676550649687641,-0.3074475690811459 -0.7676550649687641,0.09401654924378076 -0.2590574983578904,0.10567230819363671 -0.09864698028880525,-0.03901177977841874 -0.028405214140875046,-0.428964921810446 -0.08483619470406722,-0.5128305980156834 -0.12847817634298053,-0.5512747518916774 -0.2148501697175078,-0.5917836778064418 -0.7037530067555622,-0.5520451065921502 -0.7676550649687641,-0.9636984967276516 -0.7676550649687641,-0.9636984967276516 0.7676550649687783)
<img width="773" alt="Screenshot 2021-07-07 at 15 30 25" src="https://user-images.githubusercontent.com/16778892/124767639-47c22300-df38-11eb-9145-a0c1b393693e.png">

**Comment by mattbeghin** [comment]
Even simplier: 
`LINESTRING(0.9776422201600001 0.9776422201599928,0.9776422201599999 -0.977642220160007,-0.12788518519240472 -0.9776422201599928,-0.3913394510746002 -0.33861494064331055,-0.47812835166211676 -0.9776422201599928,-0.9776422201600001 -0.9776422201599928,-0.9776422201600001 0.977642220160007)`
<img width="464" alt="Screenshot 2021-07-07 at 15 43 13" src="https://user-images.githubusercontent.com/16778892/124769801-10547600-df3a-11eb-9342-4034bb4f8b4c.png">

**Comment by pierre-dejoue** [comment]
Hello,

Thanks to recent changes in the library, notably the patch on the collinearity check, the examples above are now passing.

I've created PR #44 to add those examples as part of the unit tests.
