### ISSUE TITLE
Please have a special target to run tests

### ISSUE THREAD

**Issue by yurivict** [jhasse/poly2tri#14]
The README says that OpenGL is only required for tests, yet your executable is permanently linked with it.

You should only build and install the minimal exacutable by default, and build and run test executable on request (with a special target).

**Comment by jhasse** [comment]
Which build system?

**Comment by yurivict** [comment]
waf

**Comment by jhasse** [comment]
Only Meson can be used to build the tests, sorry :/

**Comment by yurivict** [comment]
If gl is only used for tests and they can't be built - you shouldn't link with gl.

meson build doesn't install anything.

**Comment by jhasse** [comment]
GL is only used for the testbed, not for the unittests. These are the two types of "tests" that exist.

**Comment by yurivict** [comment]
So when I build and the executable it shouldn't be linked to gl?

**Comment by jhasse** [comment]
Waf builds the testbed only, so it needs to link to GL.
Meson builds a static library and the unit tests, it shouldn't need GL.
CMake only build the static library, it also shouldn't need GL.

**Comment by yurivict** [comment]
cmake also doesn't install anything.

Why don't you make cmake install what is needed, and add a target there that can test the build?

**Comment by jhasse** [comment]
No particular reason, simply haven't had the time.

**Comment by jhasse** [comment]
Thanks to #20 by @pierre-dejoue CMake can now be used to build the unit tests and the testbed. We should get rid of Waf to avoid the confusion.
