### ISSUE TITLE
Can someone clarify the relation between this project and  greenm01/poly2tri?

### ISSUE THREAD

**Issue by huangzonghao** [jhasse/poly2tri#24]
Getting confused between this one and the one here https://github.com/greenm01/poly2tri

It seems this repo is being continuously developed and the other one has been deprecated?

**Comment by jhasse** [comment]
This is a fork from greenm01/poly2tri, but I did the fork when the project was still at Google Code. It then got automatically exported to GitHub and it seems abandoned.
