### ISSUE TITLE
(void) comments;

### ISSUE THREAD

**Issue by sovietspaceship** [jhasse/poly2tri#3]
https://github.com/jhasse/poly2tri/blob/master/poly2tri/sweep/sweep_context.cc#L126
What's the point of passing `nodes` if unused, and silencing the compiler about it? Unimplemented feature? What feature? Should be documented.

**Comment by jhasse** [comment]
Yes, it's to silence the unused-parameter warning.

I don't know though why it isn't used as I didn't write that code.
