### ISSUE TITLE
Triangulation with constraints of self-intersected segments 

### ISSUE THREAD

**Issue by hph73** [jhasse/poly2tri#30]
Hi,

In my application, I need to triangulate a simply polygon with self-intersected segments as constraints. See picture below, the red lines in the triangle are constraints and they may be self-intersected. The black lines show a possible triangulation. Is it possible to reach this goal with poly2tri?

![WeChat Screenshot_20210504115200](https://user-images.githubusercontent.com/30179617/117032150-402f9500-accf-11eb-91fd-c19ee5056113.png)

**Comment by pierre-dejoue** [comment]
Hi,

The README specifically says that only simple polygons are supported. A [simple polygon](https://en.wikipedia.org/wiki/Simple_polygon) has non-intersecting line segments.
